export const Data = [
  { id: "1", title: "① 施設A", description: "施設Aの詳細です" },
  { id: "2", title: "② 施設B", description: "施設Bの詳細です" },
  { id: "3", title: "③ 施設C", description: "施設Cの詳細です" },
  { id: "4", title: "④ 施設D", description: "施設Dの詳細です" },
  { id: "5", title: "⑤ 施設E", description: "施設Eの詳細です" },
  { id: "6", title: "⑥ 施設F", description: "施設Fの詳細です" },
  { id: "7", title: "⑦ 施設G", description: "施設Gの詳細です" },
  { id: "8", title: "⑧ 施設H", description: "施設Hの詳細です" },
  { id: "9", title: "⑨ 施設I", description: "施設Iの詳細です" },
  { id: "10", title: "⑩ 施設J", description: "施設Jの詳細です" },
  { id: "11", title: "⑪ 施設K", description: "施設Kの詳細です" },
  { id: "12", title: "⑫ 施設L", description: "施設Lの詳細です" },
  { id: "13", title: "⑬ 施設M", description: "施設Mの詳細です" },
  { id: "14", title: "⑭ 施設N", description: "施設Nの詳細です" },
  { id: "15", title: "⑮ 施設O", description: "施設Oの詳細です" },
  { id: "16", title: "⑯ 施設P", description: "施設Pの詳細です" },
  { id: "17", title: "⑰ 施設Q", description: "施設Qの詳細です" },
  { id: "18", title: "⑱ 施設R", description: "施設Rの詳細です" },
  { id: "19", title: "⑲ 施設S", description: "施設Sの詳細です" },
  { id: "20", title: "⑳ 施設T", description: "施設Tの詳細です" },
  { id: "21", title: "㉑ 施設U", description: "施設Uの詳細です" },
  { id: "22", title: "㉒ 施設V", description: "施設Vの詳細です" },
  { id: "23", title: "㉓ 施設W", description: "施設Wの詳細です" },
];
